CREATE TABLE fin_faturas (
    id BIGSERIAL PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    numero_fatura VARCHAR(30) NOT NULL,
    cliente_id BIGINT NOT NULL,
    ordem_servico_id BIGINT,
    tipo_fatura VARCHAR(30),
    data_emissao DATE NOT NULL,
    data_vencimento DATE NOT NULL,
    valor_servicos DECIMAL(10,2) DEFAULT 0,
    valor_produtos DECIMAL(10,2) DEFAULT 0,
    valor_descontos DECIMAL(10,2) DEFAULT 0,
    valor_acrescimos DECIMAL(10,2) DEFAULT 0,
    valor_total DECIMAL(10,2) NOT NULL,
    valor_pago DECIMAL(10,2) DEFAULT 0,
    valor_pendente DECIMAL(10,2),
    status VARCHAR(30),
    forma_pagamento_id BIGINT,
    condicao_pagamento_id BIGINT,
    observacoes TEXT,
    observacoes_internas TEXT,
    nfe_numero VARCHAR(20),
    nfe_chave VARCHAR(44),
    nfe_url_danfe VARCHAR(500),
    data_envio_cliente TIMESTAMP,
    enviada_por_email BOOLEAN DEFAULT FALSE,
    enviada_por_whatsapp BOOLEAN DEFAULT FALSE,
    email_envio VARCHAR(255),
    whatsapp_envio VARCHAR(20),
    boleto_nosso_numero VARCHAR(50),
    boleto_url VARCHAR(500),
    pix_qr_code TEXT,
    pix_codigo VARCHAR(500),
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT,
    versao INTEGER DEFAULT 0,
    data_atualizacao TIMESTAMP,
    atualizado_por BIGINT,
    CONSTRAINT uk_fin_faturas_numero UNIQUE (empresa_id, numero_fatura),
    CONSTRAINT fk_fin_faturas_forma_pagamento FOREIGN KEY (forma_pagamento_id) REFERENCES fin_formas_pagamento(id),
    CONSTRAINT fk_fin_faturas_condicao_pagamento FOREIGN KEY (condicao_pagamento_id) REFERENCES fin_condicoes_pagamento(id)
);

CREATE INDEX idx_fin_faturas_empresa ON fin_faturas(empresa_id);
CREATE INDEX idx_fin_faturas_cliente ON fin_faturas(cliente_id);
CREATE INDEX idx_fin_faturas_os ON fin_faturas(ordem_servico_id);
