CREATE TABLE fin_contas_pagar (
    id BIGSERIAL PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    numero_titulo VARCHAR(30) NOT NULL,
    fornecedor_id BIGINT,
    tipo_titulo VARCHAR(30),
    categoria_despesa VARCHAR(100) NOT NULL,
    descricao TEXT NOT NULL,
    numero_documento VARCHAR(50),
    data_emissao DATE NOT NULL,
    data_vencimento DATE NOT NULL,
    valor_nominal DECIMAL(10,2) NOT NULL,
    valor_juros DECIMAL(8,2) DEFAULT 0,
    valor_multa DECIMAL(8,2) DEFAULT 0,
    valor_desconto DECIMAL(8,2) DEFAULT 0,
    valor_pago DECIMAL(10,2) DEFAULT 0,
    valor_pendente DECIMAL(10,2),
    data_pagamento DATE,
    forma_pagamento_id BIGINT,
    conta_bancaria_id BIGINT,
    status VARCHAR(30),
    centro_custo_id BIGINT,
    rateio_centros_custo JSONB,
    observacoes TEXT,
    anexos_comprobatorios JSONB,
    aprovado_por BIGINT,
    data_aprovacao TIMESTAMP,
    pago_por BIGINT,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT,
    versao INTEGER DEFAULT 0,
    data_atualizacao TIMESTAMP,
    atualizado_por BIGINT,
    CONSTRAINT uk_fin_contas_pagar_numero UNIQUE (empresa_id, numero_titulo),
    CONSTRAINT fk_fin_contas_pagar_forma FOREIGN KEY (forma_pagamento_id) REFERENCES fin_formas_pagamento(id),
    CONSTRAINT fk_fin_contas_pagar_conta FOREIGN KEY (conta_bancaria_id) REFERENCES fin_contas_bancarias(id),
    CONSTRAINT fk_fin_contas_pagar_centro FOREIGN KEY (centro_custo_id) REFERENCES fin_centros_custo(id)
);

CREATE INDEX idx_fin_contas_pagar_empresa ON fin_contas_pagar(empresa_id);
CREATE INDEX idx_fin_contas_pagar_fornecedor ON fin_contas_pagar(fornecedor_id);
