CREATE TABLE fin_fluxo_caixa (
    id BIGSERIAL PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    conta_bancaria_id BIGINT,
    tipo_movimentacao VARCHAR(30),
    categoria VARCHAR(100) NOT NULL,
    subcategoria VARCHAR(100),
    descricao TEXT NOT NULL,
    valor DECIMAL(12,2) NOT NULL,
    data_movimentacao DATE NOT NULL,
    data_competencia DATE,
    documento_tipo VARCHAR(50),
    documento_numero VARCHAR(50),
    documento_id BIGINT,
    centro_custo_id BIGINT,
    cliente_id BIGINT,
    fornecedor_id BIGINT,
    funcionario_id BIGINT,
    forma_pagamento_id BIGINT,
    conta_destino_id BIGINT,
    conciliado BOOLEAN DEFAULT FALSE,
    data_conciliacao TIMESTAMP,
    saldo_anterior DECIMAL(15,2),
    saldo_atual DECIMAL(15,2),
    observacoes TEXT,
    anexos JSONB,
    usuario_responsavel BIGINT NOT NULL,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    versao INTEGER DEFAULT 0,
    data_atualizacao TIMESTAMP,
    atualizado_por BIGINT,
    CONSTRAINT fk_fin_fluxo_caixa_conta FOREIGN KEY (conta_bancaria_id) REFERENCES fin_contas_bancarias(id),
    CONSTRAINT fk_fin_fluxo_caixa_centro FOREIGN KEY (centro_custo_id) REFERENCES fin_centros_custo(id),
    CONSTRAINT fk_fin_fluxo_caixa_forma FOREIGN KEY (forma_pagamento_id) REFERENCES fin_formas_pagamento(id),
    CONSTRAINT fk_fin_fluxo_caixa_destino FOREIGN KEY (conta_destino_id) REFERENCES fin_contas_bancarias(id)
);

CREATE INDEX idx_fin_fluxo_caixa_empresa ON fin_fluxo_caixa(empresa_id);
CREATE INDEX idx_fin_fluxo_caixa_data ON fin_fluxo_caixa(data_movimentacao);
