CREATE TABLE fin_nfe (
    id BIGSERIAL PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    fatura_id BIGINT,
    numero_nfe BIGINT NOT NULL,
    serie_nfe INT NOT NULL,
    chave_nfe VARCHAR(44) NOT NULL,
    tipo_operacao VARCHAR(20),
    modelo_nf VARCHAR(2) DEFAULT '55',
    data_emissao TIMESTAMP NOT NULL,
    data_saida_entrada TIMESTAMP,
    tipo_emissao VARCHAR(20),
    ambiente VARCHAR(20),
    codigo_verificacao VARCHAR(8),
    digest_value VARCHAR(28),
    protocolo_autorizacao VARCHAR(20),
    data_autorizacao TIMESTAMP,
    status_sefaz VARCHAR(50),
    motivo_status TEXT,
    xml_nfe TEXT,
    xml_cancelamento TEXT,
    xml_carta_correcao TEXT,
    danfe_url VARCHAR(500),
    qr_code TEXT,
    url_consulta VARCHAR(500),
    cancelada BOOLEAN DEFAULT FALSE,
    data_cancelamento TIMESTAMP,
    motivo_cancelamento TEXT,
    carta_correcao TEXT,
    data_carta_correcao TIMESTAMP,
    valor_total_nf DECIMAL(12,2) NOT NULL,
    valor_total_impostos DECIMAL(10,2),
    observacoes_contribuinte TEXT,
    informacoes_adicionais TEXT,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gerada_por BIGINT,
    versao INTEGER DEFAULT 0,
    data_atualizacao TIMESTAMP,
    atualizado_por BIGINT,
    CONSTRAINT uk_fin_nfe_chave UNIQUE (chave_nfe),
    CONSTRAINT fk_fin_nfe_fatura FOREIGN KEY (fatura_id) REFERENCES fin_faturas(id)
);

CREATE INDEX idx_fin_nfe_empresa ON fin_nfe(empresa_id);
CREATE INDEX idx_fin_nfe_chave ON fin_nfe(chave_nfe);
