-- V249__create_produtos_fiscais_table.sql
CREATE SEQUENCE IF NOT EXISTS produtos_fiscais_seq;

CREATE TABLE produtos_fiscais (
    id BIGINT DEFAULT nextval('produtos_fiscais_seq') PRIMARY KEY,
    produto_id BIGINT NOT NULL UNIQUE,
    empresa_id BIGINT NOT NULL,

    -- Dados básicos
    cean_trib VARCHAR(50),
    cfop VARCHAR(10),
    ncm VARCHAR(20),
    cest VARCHAR(20),
    un_comercial VARCHAR(10),
    qtd_comercial DECIMAL(15,4),
    valor_unit_comercial DECIMAL(15,4),
    un_trib VARCHAR(10),
    qtd_trib DECIMAL(15,4),
    valor_unit_tributavel DECIMAL(15,4),
    total_seguro DECIMAL(15,4),
    desconto DECIMAL(15,4),
    total_frete DECIMAL(15,4),
    outras_despesas DECIMAL(15,4),
    valor_total_bruto DECIMAL(15,4),
    ex_tipi VARCHAR(10),
    indicador_escala_relevante VARCHAR(50),
    cnpj_fabricante VARCHAR(20),
    codigo_beneficio_fiscal VARCHAR(50),
    valor_bruto_compoe_total BOOLEAN,
    pedido_compra VARCHAR(50),
    item_pedido_compra INT,
    numero_fci VARCHAR(50),
    imposto_federal_aprox DECIMAL(5,2),
    imposto_estadual_aprox DECIMAL(5,2),

    -- IPI
    ipi_sit_trib VARCHAR(100),
    ipi_classe_enquadramento VARCHAR(50),
    ipi_cod_enquadramento VARCHAR(50),
    ipi_cnpj_produtor VARCHAR(20),
    ipi_cod_selo_controle VARCHAR(50),
    ipi_qtd_selo INT,
    ipi_tipo_calculo VARCHAR(50),
    ipi_base_calc DECIMAL(15,4),
    ipi_aliquota DECIMAL(5,2),
    ipi_valor_unid_trib DECIMAL(15,4),
    ipi_valor DECIMAL(15,4),

    -- ICMS
    icms_sit_trib VARCHAR(100),
    icms_origem VARCHAR(100),
    icms_mod_bc VARCHAR(50),
    icms_red_bc DECIMAL(5,2),
    icms_base_calc DECIMAL(15,4),
    icms_aliquota DECIMAL(5,2),
    icms_motivo_desoneracao VARCHAR(50),
    icms_valor_desoneracao DECIMAL(15,4),
    icms_valor DECIMAL(15,4),
    icms_bc_st_uf_origem DECIMAL(15,4),
    icms_retido_antes DECIMAL(15,4),
    icms_bc_st_uf_dest DECIMAL(15,4),
    icms_st_uf_destino DECIMAL(15,4),
    icms_aliq_calc_credito DECIMAL(5,2),
    icms_valor_credito DECIMAL(15,4),
    icms_mod_bc_st VARCHAR(50),
    icms_margem_valor_adicionado DECIMAL(5,2),
    icms_preco_unit_pauta_st DECIMAL(15,4),
    icms_red_bc_st DECIMAL(5,2),
    icms_base_calc_st DECIMAL(15,4),
    icms_aliquota_st DECIMAL(5,2),
    icms_valor_st DECIMAL(15,4),
    icms_perc_bc_op_propria DECIMAL(5,2),
    icms_uf_pgto_st VARCHAR(2),
    icms_perc_fcp DECIMAL(5,2),
    icms_valor_fcp DECIMAL(15,4),
    icms_bc_fcp DECIMAL(15,4),
    icms_valor_bc_ret_st DECIMAL(15,4),
    icms_perc_fcp_ret_st DECIMAL(5,2),
    icms_vb_calc_fcp_ret_ant_st DECIMAL(15,4),
    icms_perc_fcp_ret_ant_st DECIMAL(5,2),
    icms_valor_bc_fcp_uf_dest DECIMAL(15,4),

    -- PIS
    pis_sit_trib VARCHAR(100),
    pis_tipo_calculo VARCHAR(50),
    pis_base_calc DECIMAL(15,4),
    pis_aliquota DECIMAL(5,2),
    pis_qv DECIMAL(15,4),
    pis_rv DECIMAL(15,4),
    pis_rvbc DECIMAL(15,4),
    pis_valor_unid_trib DECIMAL(15,4),
    pis_tipo_calculo_st VARCHAR(50),
    pis_aliquota_st DECIMAL(5,2),
    pis_valor_unid_trib_st DECIMAL(15,4),

    -- COFINS
    cofins_sit_trib VARCHAR(100),
    cofins_base_calc DECIMAL(15,4),
    cofins_aliquota DECIMAL(5,2),
    cofins_valor_unid_trib DECIMAL(15,4),
    cofins_valor DECIMAL(15,4),
    cofins_tipo_calculo_st VARCHAR(50),
    cofins_aliquota_st DECIMAL(5,2),
    cofins_valor_unid_trib_st DECIMAL(15,4),

    -- Importadas
    import_valor_bc DECIMAL(15,4),
    import_valor_desp_aduaneiras DECIMAL(15,4),
    import_valor_imposto DECIMAL(15,4),
    import_valor_iof DECIMAL(15,4),

    -- Combustíveis
    comb_cod_anp VARCHAR(50),
    comb_perc_glp DECIMAL(5,2),
    comb_cod_autorizacao_codif VARCHAR(50),
    comb_uf_consumo VARCHAR(2),
    comb_bc_cide DECIMAL(15,4),
    comb_aliquota_cide DECIMAL(15,4),
    comb_valor_cide DECIMAL(15,4),
    comb_desc_anp VARCHAR(255),
    comb_perc_glp_deriv_petroleo DECIMAL(5,2),
    comb_perc_gas_nac DECIMAL(5,2),
    comb_perc_gas_imp DECIMAL(5,2),
    comb_valor_partida DECIMAL(15,4),

    -- IBS e CBS
    ibs_sit_trib VARCHAR(50),
    ibs_classificacao_trib VARCHAR(50),
    ibs_aliquota_uf DECIMAL(5,2),
    ibs_perc_diferimento_uf DECIMAL(5,2),
    ibs_perc_red_aliquota_uf DECIMAL(5,2),
    ibs_aliquota_municipio DECIMAL(5,2),
    cbs_aliquota DECIMAL(5,2),
    cbs_perc_diferimento DECIMAL(5,2),
    cbs_perc_red_aliquota DECIMAL(5,2),

    FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE
);
