CREATE TABLE orcamento_creation_idempotency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    actor_hash VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    ordem_servico_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,
    CONSTRAINT uk_orcamento_creation_idempotency
        UNIQUE (empresa_id, actor_hash, idempotency_key)
);

CREATE INDEX idx_orcamento_creation_idempotency_order
    ON orcamento_creation_idempotency (empresa_id, ordem_servico_id);
