CREATE TABLE configuracoes_oficina (
    id BIGSERIAL PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    horario_abertura_seg_sex TIME DEFAULT '08:00:00',
    horario_fechamento_seg_sex TIME DEFAULT '18:00:00',
    horario_abertura_sabado TIME DEFAULT '08:00:00',
    horario_fechamento_sabado TIME DEFAULT '12:00:00',
    funciona_domingo BOOLEAN DEFAULT FALSE,
    horario_abertura_domingo TIME,
    horario_fechamento_domingo TIME,
    tempo_agendamento_padrao INT DEFAULT 60,
    antecedencia_minima_agendamento INT DEFAULT 24,
    permite_agendamento_online BOOLEAN DEFAULT TRUE,
    envia_lembrete_agendamento BOOLEAN DEFAULT TRUE,
    tempo_lembrete_horas INT DEFAULT 24,
    margem_lucro_padrao DECIMAL(5,2) DEFAULT 30.00,
    dias_garantia_padrao INT DEFAULT 90,
    moeda VARCHAR(3) DEFAULT 'BRL',
    formato_data VARCHAR(20) DEFAULT 'dd/MM/yyyy',
    formato_hora VARCHAR(20) DEFAULT 'HH:mm',
    timezone VARCHAR(50) DEFAULT 'America/Sao_Paulo',
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_config_oficina_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id),
    CONSTRAINT uk_config_oficina_empresa UNIQUE (empresa_id)
);
