CREATE TABLE configuracoes_fiscais (
    id BIGSERIAL PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    regime_tributario VARCHAR(20),
    anexo_simples VARCHAR(5),
    aliquota_iss DECIMAL(5,4),
    aliquota_icms DECIMAL(5,4),
    aliquota_pis DECIMAL(5,4),
    aliquota_cofins DECIMAL(5,4),
    aliquota_csll DECIMAL(5,4),
    aliquota_irpj DECIMAL(5,4),
    codigo_municipio_prestacao VARCHAR(7),
    cfop_venda_dentro_estado VARCHAR(4) DEFAULT '5102',
    cfop_venda_fora_estado VARCHAR(4) DEFAULT '6102',
    cfop_servico VARCHAR(4) DEFAULT '5933',
    serie_nfe INT DEFAULT 1,
    numeracao_nfe BIGINT DEFAULT 1,
    ambiente_nfe VARCHAR(20) DEFAULT 'HOMOLOGACAO',
    certificado_digital_a1 TEXT,
    senha_certificado VARCHAR(255),
    validade_certificado DATE,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_config_fiscal_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id),
    CONSTRAINT uk_config_fiscal_empresa UNIQUE (empresa_id)
);
