CREATE TABLE servicos (
    id BIGSERIAL PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    categoria_id BIGINT,
    codigo VARCHAR(30) UNIQUE NOT NULL,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    descricao_detalhada TEXT,
    preco_base DECIMAL(10,2) NOT NULL,
    tempo_execucao_minutos INT DEFAULT 60,
    margem_lucro_percentual DECIMAL(5,2),
    nivel_dificuldade VARCHAR(20),
    requer_elevador BOOLEAN DEFAULT FALSE,
    requer_equipamento_especial BOOLEAN DEFAULT FALSE,
    equipamentos_necessarios TEXT,
    ferramentas_necessarias TEXT,
    materiais_inclusos TEXT,
    garantia_dias INT DEFAULT 90,
    tipo_cobranca VARCHAR(20),
    unidade_cobranca VARCHAR(20) DEFAULT 'Serviço',
    pontos_fidelidade INT DEFAULT 0,
    comissao_percentual DECIMAL(5,2) DEFAULT 0,
    foto_ilustrativa_url VARCHAR(500),
    video_explicativo_url VARCHAR(500),
    instrucoes_execucao TEXT,
    checklist_execucao JSON,
    ativo BOOLEAN DEFAULT TRUE,
    destaque BOOLEAN DEFAULT FALSE,
    promocional BOOLEAN DEFAULT FALSE,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT,
    atualizado_por BIGINT,
    versao INT DEFAULT 0,
    CONSTRAINT fk_servico_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id),
    CONSTRAINT fk_servico_categoria FOREIGN KEY (categoria_id) REFERENCES categorias_servicos(id)
);
