CREATE TABLE servicos_precos (
    id BIGSERIAL PRIMARY KEY,
    servico_id BIGINT NOT NULL,
    tipo_veiculo_id BIGINT,
    categoria_veiculo VARCHAR(20),
    marca_id BIGINT,
    modelo_id BIGINT,
    ano_inicial INT,
    ano_final INT,
    preco DECIMAL(10,2) NOT NULL,
    preco_promocional DECIMAL(10,2),
    data_inicio_promocao DATE,
    data_fim_promocao DATE,
    observacoes TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT,
    atualizado_por BIGINT,
    versao INT DEFAULT 0,
    CONSTRAINT fk_servico_preco_servico FOREIGN KEY (servico_id) REFERENCES servicos(id),
    CONSTRAINT fk_servico_preco_marca FOREIGN KEY (marca_id) REFERENCES marcas_veiculos(id),
    CONSTRAINT fk_servico_preco_modelo FOREIGN KEY (modelo_id) REFERENCES modelos_veiculos(id)
);
