CREATE TABLE produtos (
    id BIGSERIAL PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    categoria_id BIGINT,
    codigo_interno VARCHAR(50) UNIQUE NOT NULL,
    codigo_barras VARCHAR(50),
    codigo_fabricante VARCHAR(50),
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    descricao_detalhada TEXT,
    marca VARCHAR(100),
    modelo VARCHAR(100),
    aplicacao TEXT,
    especificacoes_tecnicas JSON,
    unidade_medida_id BIGINT,
    peso_liquido DECIMAL(8,3),
    peso_bruto DECIMAL(8,3),
    dimensoes_comprimento DECIMAL(8,2),
    dimensoes_largura DECIMAL(8,2),
    dimensoes_altura DECIMAL(8,2),
    preco_custo DECIMAL(10,4) NOT NULL,
    preco_venda DECIMAL(10,2) NOT NULL,
    margem_lucro_percentual DECIMAL(5,2),
    estoque_minimo DECIMAL(10,2) DEFAULT 0,
    estoque_maximo DECIMAL(10,2),
    ponto_reposicao DECIMAL(10,2),
    controla_lote BOOLEAN DEFAULT FALSE,
    controla_validade BOOLEAN DEFAULT FALSE,
    dias_validade INT,
    ncm VARCHAR(8),
    cest VARCHAR(7),
    origem_produto VARCHAR(1),
    foto_principal_url VARCHAR(500),
    garantia_meses INT DEFAULT 0,
    observacoes TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    destaque BOOLEAN DEFAULT FALSE,
    promocional BOOLEAN DEFAULT FALSE,
    pontos_fidelidade INT DEFAULT 0,
    comissao_venda_percentual DECIMAL(5,2),
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT,
    atualizado_por BIGINT,
    versao INT DEFAULT 0,
    CONSTRAINT fk_produto_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id),
    CONSTRAINT fk_produto_categoria FOREIGN KEY (categoria_id) REFERENCES categorias_produtos(id),
    CONSTRAINT fk_produto_unidade FOREIGN KEY (unidade_medida_id) REFERENCES unidades_medida(id)
);
