CREATE TABLE promocoes (
    id BIGSERIAL PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    tipo_promocao VARCHAR(30),
    valor_desconto DECIMAL(10,2),
    percentual_desconto DECIMAL(5,2),
    quantidade_leve INT,
    quantidade_pague INT,
    valor_minimo_pedido DECIMAL(10,2),
    data_inicio TIMESTAMP NOT NULL,
    data_fim TIMESTAMP NOT NULL,
    limite_uso_total INT,
    limite_uso_cliente INT,
    vezes_utilizada INT DEFAULT 0,
    codigo_cupom VARCHAR(20),
    aplicacao_automatica BOOLEAN DEFAULT FALSE,
    categorias_aplicaveis JSON,
    produtos_aplicaveis JSON,
    clientes_aplicaveis JSON,
    canais_venda JSON,
    observacoes TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT,
    versao INT DEFAULT 0,
    CONSTRAINT fk_promocao_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id)
);
