-- Criação da tabela empresa (tenant)
CREATE TABLE IF NOT EXISTS empresa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_fantasia VARCHAR(255),
    razao_social VARCHAR(255),
    cnpj VARCHAR(20) NOT NULL,
    inscricao_estadual VARCHAR(30),
    inscricao_municipal VARCHAR(30),
    email VARCHAR(120),
    telefone VARCHAR(30),
    site VARCHAR(120),
    data_abertura DATE,
    observacoes VARCHAR(2000),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_cadastro TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP NULL,
    criado_por BIGINT NULL,
    atualizado_por BIGINT NULL,
    versao INT NULL
);

-- Índices e restrições
CREATE UNIQUE INDEX IF NOT EXISTS uk_empresa_cnpj ON empresa(cnpj);
CREATE INDEX IF NOT EXISTS idx_empresa_razao_social ON empresa(razao_social);
CREATE INDEX IF NOT EXISTS idx_empresa_nome_fantasia ON empresa(nome_fantasia);