server {
    listen 80;
    server_name 209.50.229.218;

    # Backend API
    location /api/ {
        proxy_pass http://neritech-api:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Health Check simplificado
    location /health {
        access_log off;
        return 200 'OK';
    }

    # Erros
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
