package com.neritech.saas.veiculo.domain.enums;

public enum TipoFoto {
    EXTERNA_FRENTE, EXTERNA_TRAS, EXTERNA_LATERAL_ESQUERDA, EXTERNA_LATERAL_DIREITA, INTERNA_PAINEL, INTERNA_BANCOS,
    MOTOR, PORTA_MALAS, DEFEITO, OUTROS
}
