package com.neritech.saas.produtoServico.dto;

import com.neritech.saas.produtoServico.domain.enums.OrigemProduto;
import java.math.BigDecimal;

public record ProdutoResponse(
                Long id,
                Long empresaId,
                Long categoriaId,
                String categoriaNome,
                Long unidadeMedidaId,
                String unidadeMedidaSigla,
                String codigoInterno,
                String codigoBarras,
                String codigoFabricante,
                String nome,
                String descricao,
                String descricaoDetalhada,
                String marca,
                String modelo,
                String aplicacao,
                String especificacoesTecnicas,
                BigDecimal pesoLiquido,
                BigDecimal pesoBruto,
                BigDecimal dimensoesComprimento,
                BigDecimal dimensoesLargura,
                BigDecimal dimensoesAltura,
                BigDecimal precoCusto,
                BigDecimal precoVenda,
                BigDecimal margemLucroPercentual,
                BigDecimal estoqueMinimo,
                BigDecimal estoqueMaximo,
                BigDecimal pontoReposicao,
                Boolean controlaLote,
                Boolean controlaValidade,
                Integer diasValidade,
                String ncm,
                String cest,
                String origemProduto,
                String fotoPrincipalUrl,
                Integer garantiaMeses,
                String observacoes,
                Boolean ativo,
                Boolean destaque,
                Boolean promocional,
                Integer pontosFidelidade,
                BigDecimal comissaoVendaPercentual,
                BigDecimal quantidadeEstoque) {
}
